### ISSUE TITLE
Bib file is not successfully converted 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/ccg-bibfiles#8]
@schen149 
when I try your script on my citations, here is the error I get: 
```bash 
Daniels-MacBook-Pro-4:dswmhrjtfstcmvdrzdnbbnkzkbvwxjdp daniel$ python3.7  ccg_style_bib_converter.py ref2.bib ref3.bib outputmapping.txt
Overwritting existing string for key: tassp.
Overwritting existing string for key: it.
Overwritting existing string for key: jacm.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
Entry type other not standard. Not considered.
{'AI': 'Artificial Intelligence', 'CACM': 'Communications of the ACM', 'CSL': 'Computer Speech and Language', 'CL': 'Computational Linguistics', 'INFCTRL': 'Information and Control', 'IT': 'IEEE Transactions on Information Theory', 'JACM': 'Journal of the ACM', 'JAIR': 'Journal of AI Research', 'JMLR': 'Journal of Machine Learning Research', 'ML': 'Machine Learning', 'NLE': 'Journal of Natural Language Engineering', 'MM': 'IEEE Transactions on Multimedia', 'PAMI': 'IEEE Transactions on Pattern Analysis and Machine Intelligence', 'SIJAD': 'SIAM Journal of Algebraic and Discrete Methods', 'SIJC': 'SIAM Journal of Computing', 'TASSP': 'IEEE Transactions on Acoustics, speech, and Signal Processing', 'TCS': 'Theoretical Computer Science', 'AAAI': 'Proceedings of the National Conference on Artificial Intelligence (AAAI)', 'ANLP': 'Proc. of ACL Conference on Applied Natural Language Processing', 'ARPA': 'Proc. of the ARPA Workshop on Human Language Technology', 'ACCV': 'Proceedings of the Asian Conference on Computer Vision (ACCV)', 'AISTAT': 'Proceedings of the International Workshop on Artificial Intelligence and Statistics', 'ALT': 'Proc. of the International Workshop on Algorithmic Learning Theory (ALT)', 'COLING': 'Proc.  the International Conference on Computational Linguistics (COLING)', 'ACL': 'Proc. of the Annual Meeting of the Association of Computational Linguistics (ACL)', 'COLT': 'Proc. of the Annual ACM Workshop on Computational Learning Theory (COLT)', 'CONLL': 'Proc. of the Annual Conference on Computational Natural Language Learning (CoNLL)', 'CVPR': 'The IEEE Conference on Computer Vision and Pattern Recognition (CVPR)', 'DARPA': 'Proc. of the DARPA Workshop on Speech and Natural Language', 'ECML': 'Proc. of the European Conference on Machine Learning (ECML)', 'FOCS': 'IEEE Symp. of Foundation of Computer Science', 'ECCV': 'Proc. of the European Conference on Computer Vision (ECCV)', 'IAAI': 'Proceedings of the National Conference on Innovative Applications of Artificial Intelligence (IAAI)', 'ICML': 'Proc. of the International Conference on Machine Learning (ICML)', 'ICASSP': 'Proc. of ICASSP', 'IJCAI': 'Proc. of the International Joint Conference on Artificial Intelligence (IJCAI)', 'IJCNLP': 'Proc. of the International Joint Conference on Natural Language Processing (IJCNLP)', 'ILP': 'Proc. of the International Conference Inductive Logic Programming', 'IPW': 'Proc. of the International Parsing Workshop', 'IWPT': 'Proc. of the International Workshop of Parsing Technology', 'ISMB': 'The International Conference on Intelligent Systems for Molecular Biology', 'KR': 'Proc. of the International Conference on the Principles of Knowledge Representation and Reasoning', 'NAACL': 'Proc. of the Annual Meeting of the North American Association of Computational Linguistics (NAACL)', 'NIPS': 'The Conference on Advances in Neural Information Processing Systems (NIPS)', 'SIGIR': 'Proc. of International Conference on Research and Development in Information Retrieval, SIGIR', 'SIGDAT': 'Proc. of the Conference on Empirical Methods for Natural Language Processing (EMNLP)', 'EMNLP': 'Proc. of the Conference on Empirical Methods for Natural Language Processing (EMNLP)', 'STOC': 'ACM Symp. of the Theory of Computing', 'TMI': 'Proc. of the International Conference on Theoretical and Methodological Issues in Machine Translation', 'UWOED': 'Proc. of the Annual Conference of the UW Center for the New OED and Text Research', 'WWW': 'The International World Wide Web Conference', 'CAMBRIDGE': 'Cambridge University Press', 'BENJAMIN': 'Benjamin/Cummings Publishing Company, Inc.', 'MIT': 'MIT Press'}
Traceback (most recent call last):
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bibdatabase.py", line 114, in expand_string
    self.strings[name])
KeyError: 'dec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ccg_style_bib_converter.py", line 176, in <module>
    results = convert_entry_to_ccg_style(open(original_bib_file).read())
  File "ccg_style_bib_converter.py", line 48, in convert_entry_to_ccg_style
    bib_db = bibtexparser.loads(bib_str, parser)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/__init__.py", line 48, in loads
    return parser.parse(bibtex_str)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bparser.py", line 155, in parse
    self._expr.parseFile(bibtex_file_obj)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bibtexexpression.py", line 286, in parseFile
    return self.main_expression.parseFile(file_obj, parseAll=True)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 2207, in parseFile
    return self.parseString(file_contents, parseAll)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1666, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4094, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4033, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 3618, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 3483, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 3618, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 3483, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 3483, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4094, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 4033, in parseImpl
    loc, tmptokens = self_expr_parse( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 3483, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 3805, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 3483, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1412, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 3618, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1445, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/pyparsing.py", line 1082, in wrapper
    ret = func(*args[limit[0]:])
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bibtexexpression.py", line 283, in _string_expr_parse_action
    return self._string_expr_parse_action_fun(s, l, t)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bparser.py", line 196, in <lambda>
    BibDataStringExpression.expression_if_needed(t)))
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bparser.py", line 190, in <lambda>
    maybe_interpolate = lambda expr: as_text(expr)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bibdatabase.py", line 277, in as_text
    return text_string_or_expression.get_value()
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bibdatabase.py", line 238, in get_value
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bibdatabase.py", line 238, in <listcomp>
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bibdatabase.py", line 204, in expand_string
    return string_or_bibdatastring.get_value()
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bibdatabase.py", line 185, in get_value
    return self._bibdatabase.expand_string(self.name)
  File "/Users/daniel/miniconda3/lib/python3.7/site-packages/bibtexparser/bibdatabase.py", line 116, in expand_string
    raise(UndefinedString(name))
bibtexparser.bibdatabase.UndefinedString: 'dec'
Daniels-MacBook-Pro-4:dswmhrjtfstcmvdrzdnbbnkzkbvwxjdp daniel$ 
```

Any thoughts what's going wrong? 
Btw, this citation file is already normalized by JabRef. 
Here is the bibfile btw: https://www.dropbox.com/s/1kmssw2w3r82eba/ref2.bib?dl=0

**Comment by danyaljj** [comment]
Figured the issue. 
The bibfile contains some illegal values.  For instance, `month     = dec`, which have to be manually fixed.
